manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch  # ←ここを main から v0.3-branch に変更
      import: app/west.yml
  self:
    path: config
