manifest:
  remotes:
    - name: zmkfirmware
      url_base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2  # mainからv0.2に変更することで古い定義との互換性を保ちます
      import: app/west.yml
  self:
    path: config
